services:
  weak-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  rabbitmq:
    image: rabbitmq:4.2.5-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
